[package]
name = "cargo-mutants"
version = "0.1.0"
edition = "2018"
authors = ["Martin Pool"]
license = "MIT"
description = "Find inadequately-tested code that can be removed without any tests failing."
repository = "https://github.com/sourcefrog/cargo-mutants"
categories = ["development-tools::testing"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
argh = "0.1.6"
console = "0.15"
itertools = "0.10"
path-slash = "0.1.4"
quote = "1.0"
similar = "2.0"
tempfile = "3.2"
walkdir = "2.3"
serde_json = "1.0.68"
indicatif = "0.16"

[dependencies.cp_r]
version = "0.4.0"
# path = "../cp_r"
# git = "https://github.com/sourcefrog/cp_r"

[dependencies.serde]
version = "1.0.130"
features = ["derive"]

[dependencies.syn]
version = "1.0.81"
features = ["full", "extra-traits", "visit"]

[dependencies.proc-macro2]
features = ["span-locations"]
version = "1.0.29"

[dev-dependencies]
assert_cmd = "2.0"
insta = "1.8"
lazy_static = "1.4"
predicates = "2.0"
pretty_assertions = "0.7.2"
regex = "1.5"

[workspace]
members = [
    "mutants_attrs",
    # TODO: Re-enable this when the tests are checked by the real integration tests, but
    # skipped by `cargo test --workspace`. (It's complicated!)
    # "testdata/tree/already_failing_tests",
    "testdata/tree/could_hang/",
    "testdata/tree/factorial",
    "testdata/tree/well_tested",
]
